{% set version = "0.0.1" %}
{% set sha256 = "1792c40c261df7dd26f4eec6adf58a5516dc265a72f0dd9744e013bd6b1c0a5c" %}

package:
  name: proteomiqon-joinquantpepionswithproteins
  version: '{{ version }}'

source:
  url: https://www.nuget.org/api/v2/package/ProteomIQon.JoinQuantPepIonsWithProteins/{{ version }}
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  script:
    - dotnet tool install --add-source $SRC_DIR --tool-path $PREFIX/bin --version {{ version }} ProteomIQon.JoinQuantPepIonsWithProteins

requirements:
  host:
    - dotnet-sdk
  run:
    - dotnet-runtime

test:
  commands:
    - proteomiqon-joinquantpepionswithproteins --help

about:
  home: https://csbiology.github.io/ProteomIQon/
  license: MIT
  summary: TODO
  description: |
    TODO
  dev_url: https://github.com/CSBiology/ProteomIQon
  doc_url: https://csbiology.github.io/ProteomIQon/tools/JoinQuantPepIonsWithProteins.html