{% set version = "0.0.1" %}
{% set sha256 = "3514cbfd13ee4620bf305a246c7328e62f88687f30de7a19c6fedc5d1267f059" %}

package:
  name: proteomiqon-labelfreeproteinquantification
  version: '{{ version }}'

source:
  url: https://www.nuget.org/api/v2/package/ProteomIQon.LabelFreeProteinQuantification/{{ version }}
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  script:
    - dotnet tool install --add-source $SRC_DIR --tool-path $PREFIX/bin --version {{ version }} ProteomIQon.LabelFreeProteinQuantification

requirements:
  host:
    - dotnet-sdk
  run:
    - dotnet-runtime

test:
  commands:
    - proteomiqon-labelfreeproteinquantification --help

about:
  home: https://csbiology.github.io/ProteomIQon/
  license: MIT
  summary: TODO
  description: |
    TODO
  dev_url: https://github.com/CSBiology/ProteomIQon
  doc_url: https://csbiology.github.io/ProteomIQon/tools/LabelFreeProteinQuantification.html