{% set version = "0.0.1" %}
{% set sha256 = "513dd36981cc4f834ec46fff32a19c613c271ac7c8996c7367ce4d0308bccf67" %}

package:
  name: proteomiqon-labeledproteinquantification
  version: '{{ version }}'

source:
  url: https://www.nuget.org/api/v2/package/ProteomIQon.LabeledProteinQuantification/{{ version }}
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  script:
    - dotnet tool install --add-source $SRC_DIR --tool-path $PREFIX/bin --version {{ version }} ProteomIQon.LabeledProteinQuantification

requirements:
  host:
    - dotnet-sdk
  run:
    - dotnet-runtime

test:
  commands:
    - proteomiqon-labeledproteinquantification --help

about:
  home: https://csbiology.github.io/ProteomIQon/
  license: MIT
  summary: TODO
  description: |
    TODO
  dev_url: https://github.com/CSBiology/ProteomIQon
  doc_url: https://csbiology.github.io/ProteomIQon/tools/LabeledProteinQuantification.html
